on: issue_comment
name: Issue Comments for approve
jobs:
  check_comments:
    name: Check comments for /approve
    runs-on: ubuntu-latest
    steps:
      - name: Check for Command
        id: command
        uses: xt0rted/slash-command-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          command: approve
          reaction: "true"
          reaction-type: "eyes"
          allow-edits: "false"
          permission-level: admin
  approve:
    runs-on: ubuntu-latest
    needs: [check_comments]
    steps:  
      - name: Approve Pull Request
        uses: juliangruber/approve-pull-request-action@v1.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.client_payload.github.payload.issue.number }}
  commentApprove:
    runs-on: ubuntu-latest
    needs: [approve]
    needs: [check_comments, approve]
    steps:
      - name: Add reaction on success
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: laugh
